if(NOT DEFINED EXECUTABLE OR NOT DEFINED DESTINATION OR NOT DEFINED MINGW_BIN_DIR)
    message(FATAL_ERROR "EXECUTABLE, DESTINATION, and MINGW_BIN_DIR must be set.")
endif()

file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES "${EXECUTABLE}"
    DIRECTORIES "${MINGW_BIN_DIR}"
    RESOLVED_DEPENDENCIES_VAR RUNTIME_DEPENDENCIES
    UNRESOLVED_DEPENDENCIES_VAR UNRESOLVED_DEPENDENCIES
    POST_EXCLUDE_REGEXES ".*[/\\\\][Ww]indows[/\\\\][Ss]ystem32[/\\\\].*"
)

if(UNRESOLVED_DEPENDENCIES)
    message(FATAL_ERROR "Unresolved runtime dependencies: ${UNRESOLVED_DEPENDENCIES}")
endif()

foreach(DEPENDENCY IN LISTS RUNTIME_DEPENDENCIES)
    file(COPY "${DEPENDENCY}" DESTINATION "${DESTINATION}")
endforeach()
